version: "3.4"

services:
  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: algafood-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data_container:/var/lib/mysql"

volumes:
  mysql_data_container:
    driver: local

networks:
  default:
    external:
      name: algafoodNet